spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts Microservice related Prod APIs"
  contactDetails:
    name: "Huy Cao Product Owner"
    email: "caogiahuy77@yahoo.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-8371
